#!/usr/bin/env node

const { execSync } = require('child_process');
const os = require('os');
const path = require('path');

const time = Date.now();
// home directory handling
const fileName = path.join(os.homedir(), '.git-shots', `${time}.jpg`);
execSync(`imagesnap -w 2 "${fileName}"`);

